development:
  name: ui
  url:  http://dev.ui.mindpin.com/
  master_url:  http://dev.2010.mindpin.com/

test:
  name: ui
  url:  http://dev.ui.mindpin.com/
  master_url:  http://dev.2010.mindpin.com/

production:
  name: ui
  url:  http://ui.mindpin.com/
  master_url:  http://2010.mindpin.com/